include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = SailboatGNUstep

SailboatGNUstep_HEADER_FILES = src/objc/Sailboat.h
SailboatGNUstep_OBJC_FILES =  src/objc/Sailboat.m src/objc/main.m

ADDITIONAL_OBJCFLAGS = -DWINGS
ADDITIONAL_CFLAGS = -DWINGS

include $(GNUSTEP_MAKEFILES)/tool.make

